name: Continuous Delivery

on:
  push:
    branches:
      - '**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }},

jobs:
  golangci:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Source Code
        uses: actions/checkout@v2.4.0
      -
        name: Install Go Package
        uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.21.x"
      -
        name: Run Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: "v1.43.0"
          args: --timeout 4m
  build:
    name: Build binaries
    needs: golangci
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Source Code
        uses: actions/checkout@v2.4.0
      -
        name: Install Go Package
        uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.21.x"
      -
       name: GoReleaser env
       run: |
         echo GOPATH=$(go env GOPATH) >> $GITHUB_ENV
         echo PWD=$(pwd) >> $GITHUB_ENV
      -
        name: Go Releaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --skip-validate --rm-dist --snapshot
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Metadata for the image
        id: meta
        uses: docker/metadata-action@v3.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}
      -
        name: Build container
        uses: docker/build-push-action@v2.7.0
        with:
          platforms: "linux/amd64, linux/arm64"
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
